http://localhost:5173/api/user/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNzU2MTc5NDBAcXEuY29tIiwiZXhwIjoxNzU5OTk3NTQxLCJpYXQiOjE3NTk5OTAzNDF9.O3xnItb5VfuFfKIMpcz6D6snhjfE7a1eVA9XL6wC5tQ




###
https://hero.z2c.shop/api/user/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNzU2MTc5NDBAcXEuY29tIiwiZXhwIjoxNzYwMDAyNTEwLCJpYXQiOjE3NTk5OTUzMTB9.82mtKzp9j4TaFhPYLn4GM7EKGvUSLnue6TNIDGJVfxo
