http://localhost:5173/api/user/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNzU2MTc5NDBAcXEuY29tIiwiZXhwIjoxNzYwMDAyNTEwLCJpYXQiOjE3NTk5OTUzMTB9.82mtKzp9j4TaFhPYLn4GM7EKGvUSLnue6TNIDGJVfxo



###
https://hero.z2c.shop/api/user/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNzU2MTc5NDBAcXEuY29tIiwiZXhwIjoxNzYwMDA5ODgxLCJpYXQiOjE3NjAwMDI2ODF9.bFgMD_FxNDSKETzABG7yRXB_L59fBhhhCDY31C_H11Q
###

ali.z2c.shop:9000