@token =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNzU2MTc5NDBAcXEuY29tIiwiZXhwIjoxNzYwMDAyNTEwLCJpYXQiOjE3NTk5OTUzMTB9.82mtKzp9j4TaFhPYLn4GM7EKGvUSLnue6TNIDGJVfxo

###
Get  http://localhost:5173/x/todo/Task/List
Content-Type: application/json
Authorization: Bearer {{token}}


###
Get  http://localhost:5173/x/todo/Group/Explore
Content-Type: application/json
Authorization: Bearer {{token}}



###
Get  https://hero.z2c.shop/x/todo/Group/Explore
Content-Type: application/json
Authorization: Bearer {{token}}
